import { Filter, QrCode, Search } from "lucide-react";
import type { AssignableAsset } from "./types";
import { assets } from "./types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export function SelectAssetStep({ selected, onSelect }: { selected?: AssignableAsset; onSelect: (asset: AssignableAsset) => void }) {
  return <section className="space-y-4"><div><h2 className="text-base font-semibold">1. Select Asset</h2><p className="text-xs text-muted-foreground">Search or scan an available asset to assign.</p></div>
    <div className="flex border-b"><button className="border-b-2 border-primary px-3 py-2 text-xs font-medium text-primary">Search Asset</button><button className="flex items-center gap-1 px-3 py-2 text-xs text-muted-foreground"><QrCode className="size-3.5" />Scan QR / Barcode</button></div>
    <div className="grid gap-2 md:grid-cols-[1fr_140px_130px_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search by asset tag, property number, serial number..." /></div><Select defaultValue="all"><SelectTrigger><SelectValue placeholder="Category" /></SelectTrigger><SelectContent><SelectItem value="all">All Categories</SelectItem><SelectItem value="laptop">Laptop</SelectItem><SelectItem value="peripheral">Peripheral</SelectItem></SelectContent></Select><Select defaultValue="available"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="available">Available</SelectItem></SelectContent></Select><Button variant="outline"><Filter className="mr-1 size-3.5" />Filters</Button></div>
    <div className="rounded-md border"><Table><TableHeader><TableRow>{["", "Asset Tag", "Property No.", "Asset Name", "Category", "Serial Number", "Location", ""].map((heading, index) => <TableHead key={`${heading}-${index}`} className="text-[11px]">{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{assets.map((asset) => <TableRow key={asset.id} data-state={selected?.id === asset.id ? "selected" : undefined}><TableCell><input type="radio" name="asset" checked={selected?.id === asset.id} onChange={() => onSelect(asset)} /></TableCell><TableCell className="font-mono text-xs text-primary">{asset.assetTag}</TableCell><TableCell className="font-mono text-xs">{asset.propertyNumber}</TableCell><TableCell className="font-medium">{asset.name}</TableCell><TableCell>{asset.category}</TableCell><TableCell className="font-mono text-xs">{asset.serialNumber}</TableCell><TableCell>{asset.location}</TableCell><TableCell><Button size="xs" variant="outline" onClick={() => onSelect(asset)}>View</Button></TableCell></TableRow>)}</TableBody></Table></div>
    {selected && <div className="rounded-md border border-info-border bg-info p-3 text-info-foreground"><p className="mb-2 text-xs font-semibold">Selected Asset</p><div className="grid gap-3 text-xs sm:grid-cols-5"><div><p className="font-medium">{selected.name}</p><Badge variant="success" className="mt-1">Available</Badge></div><p><span className="text-info-foreground/70">Category</span><br />{selected.category}</p><p><span className="text-info-foreground/70">Serial No.</span><br />{selected.serialNumber}</p><p><span className="text-info-foreground/70">Property No.</span><br />{selected.propertyNumber}</p><p><span className="text-info-foreground/70">Location</span><br />{selected.location}</p></div></div>}
  </section>;
}
