"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { zodResolver } from "@hookform/resolvers/zod"
import type { CreateDepartmentInput, Department, UpdateDepartmentInput } from "@repo/trpc/schemas"
import { Edit3, Plus, Search, ToggleLeft } from "lucide-react"
import { startTransition, useMemo, useState } from "react"
import { useForm } from "react-hook-form"
import { toast } from "sonner"
import { z } from "zod"

const schema = z.object({ code: z.string().min(1, "Department code is required").regex(/^[A-Za-z0-9_-]+$/, "Use only letters, numbers, hyphens, or underscores"), name: z.string().min(1, "Department name is required"), type: z.enum(["Academic", "Administrative", "Support Office"]) })
type Values = z.infer<typeof schema>
type Result = { ok: boolean; message?: string }

function DepartmentDialog({ record, open, onOpenChange, onCreate, onUpdate }: { record: Department | null; open: boolean; onOpenChange: (open: boolean) => void; onCreate: (input: CreateDepartmentInput) => Promise<Result>; onUpdate: (input: UpdateDepartmentInput) => Promise<Result> }) {
  const form = useForm<Values>({ resolver: zodResolver(schema), values: record ? { code: record.code, name: record.name, type: record.type as Values["type"] } : { code: "", name: "", type: "Academic" } })
  const [saving, setSaving] = useState(false)
  const submit = async (values: Values) => { setSaving(true); const result = record ? await onUpdate({ id: record.id, ...values }) : await onCreate(values); setSaving(false); if (!result.ok) return toast.error(result.message ?? "Unable to save department."); toast.success(`Department successfully ${record ? "updated" : "created"}.`); onOpenChange(false) }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{record ? "Edit Department" : "Create Department"}</DialogTitle><DialogDescription>Departments are reusable reference data for people, assets, requests, and reporting.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={form.handleSubmit(submit)}><div><Label>Department Code</Label><Input className="mt-1" {...form.register("code")} />{form.formState.errors.code && <p className="mt-1 text-xs text-destructive">{form.formState.errors.code.message}</p>}</div><div><Label>Department Name</Label><Input className="mt-1" {...form.register("name")} />{form.formState.errors.name && <p className="mt-1 text-xs text-destructive">{form.formState.errors.name.message}</p>}</div><div><Label>Organizational Type</Label><Select value={form.watch("type")} onValueChange={(type) => form.setValue("type", type as Values["type"])}><SelectTrigger className="mt-1 w-full"><SelectValue /></SelectTrigger><SelectContent>{["Academic", "Administrative", "Support Office"].map((type) => <SelectItem key={type} value={type}>{type}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving..." : record ? "Save Department" : "Create Department"}</Button></DialogFooter></form></DialogContent></Dialog>
}

export function DepartmentsContentSection({ departments, error, onCreate, onUpdate, onSetStatus }: { departments: Department[]; error?: string; onCreate: (input: CreateDepartmentInput) => Promise<Result>; onUpdate: (input: UpdateDepartmentInput) => Promise<Result>; onSetStatus: (input: { id: number; status: "active" | "inactive" }) => Promise<Result> }) {
  const [search, setSearch] = useState(""); const [dialog, setDialog] = useState<{ open: boolean; record: Department | null }>({ open: false, record: null }); const filtered = useMemo(() => departments.filter((department) => `${department.code} ${department.name} ${department.type}`.toLowerCase().includes(search.toLowerCase())), [departments, search]); const toggle = (record: Department) => startTransition(async () => { const status = record.status === "active" ? "inactive" : "active"; const result = await onSetStatus({ id: record.id, status }); result.ok ? toast.success(`Department ${status === "active" ? "activated" : "deactivated"}.`) : toast.error(result.message ?? "Unable to update department.") })
  return <div className="space-y-5"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Departments</h2><p className="text-sm text-muted-foreground">Organizational units used by users, assets, and requests.</p></div><Button onClick={() => setDialog({ open: true, record: null })}><Plus /> Create Department</Button></div><div className="grid gap-3 sm:grid-cols-3">{[[departments.length, "Total Departments"], [departments.filter((item) => item.status === "active").length, "Active Departments"], [departments.filter((item) => item.status === "inactive").length, "Inactive Departments"]].map(([value, label]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</div><Card><CardContent className="p-0"><div className="flex justify-between border-b p-4"><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search departments..." /></div><span className="text-xs text-muted-foreground">{filtered.length} results</span></div>{error ? <p className="p-6 text-sm text-destructive">{error}</p> : <Table><TableHeader><TableRow>{["Code", "Department", "Type", "Status", "Actions"].map((heading) => <TableHead key={heading}>{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.length ? filtered.map((department) => <TableRow key={department.id}><TableCell className="font-mono text-xs text-primary">{department.code}</TableCell><TableCell className="font-medium">{department.name}</TableCell><TableCell>{department.type}</TableCell><TableCell><Badge variant={department.status === "active" ? "success" : "secondary"}>{department.status}</Badge></TableCell><TableCell className="flex gap-1"><Button size="xs" variant="ghost" onClick={() => setDialog({ open: true, record: department })}><Edit3 /> Edit</Button><Button size="xs" variant="ghost" onClick={() => toggle(department)}><ToggleLeft /> {department.status === "active" ? "Deactivate" : "Activate"}</Button></TableCell></TableRow>) : <TableRow><TableCell colSpan={5} className="h-28 text-center text-muted-foreground">No departments found.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card><DepartmentDialog record={dialog.record} open={dialog.open} onOpenChange={(open) => setDialog((current) => ({ ...current, open }))} onCreate={onCreate} onUpdate={onUpdate} /></div>
}
