"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { Check, Clock3, History, Laptop } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AssetTransferHeaderSection } from "./asset-transfer-header-section";
import { AssetTransferStepper } from "./asset-transfer-stepper";
import { SelectTransferAssetStep } from "./select-asset-step";
import { TransferDetailsForm } from "./transfer-details-form";
import { transferTerms, type NewAssignment, type TransferAsset } from "./types";

const initialTransfer: NewAssignment = { custodian: "", department: "", office: "", location: "", transferDate: new Date().toISOString().slice(0, 10), reason: "", remarks: "" };
export function AssetTransferContentSection() {
  const [step, setStep] = useState(0); const [asset, setAsset] = useState<TransferAsset>(); const [details, setDetails] = useState<NewAssignment>(initialTransfer); const [terms, setTerms] = useState([false, false, false, false]); const [completed, setCompleted] = useState(false); const [pending, startTransition] = useTransition();
  const valid = step === 0 ? Boolean(asset) : step === 1 ? Boolean(details.custodian && details.department && details.office && details.location && details.transferDate && details.reason) : step === 2 ? terms.every(Boolean) : Boolean(asset && details.custodian && terms.every(Boolean));
  function next() { if (!valid) { toast.error("Complete the required information before continuing."); return; } setStep((current) => Math.min(3, current + 1)); }
  function complete() { startTransition(async () => { await new Promise((resolve) => window.setTimeout(resolve, 450)); setCompleted(true); toast.success("Demo transfer completed. No backend records were changed."); }); }
  function reset() { setStep(0); setAsset(undefined); setDetails(initialTransfer); setTerms([false, false, false, false]); setCompleted(false); }
  return <main className="mx-auto max-w-[1440px] space-y-5"><AssetTransferHeaderSection enabled={Boolean(asset && details.custodian && terms.every(Boolean))} onReview={() => { if (asset && details.custodian && terms.every(Boolean)) setStep(3); }} onCancel={reset} /><AssetTransferStepper current={step} onSelect={setStep} />{completed && <div className="rounded-md border border-success-border bg-success p-3 text-sm text-success-foreground">The demo transfer is complete. The asset remains assigned and its new assignment is recorded locally in this workflow.</div>}<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]"><Card><CardContent className="p-5">{step === 0 && <SelectTransferAssetStep selected={asset} onSelect={setAsset} />}{step === 1 && asset && <TransferDetailsForm asset={asset} value={details} onChange={setDetails} />}{step === 2 && <TermsStep terms={terms} setTerms={setTerms} />}{step === 3 && asset && <ReviewStep asset={asset} details={details} accepted={terms.every(Boolean)} />}<div className="mt-5 flex justify-between border-t pt-4"><Button variant="outline" disabled={step === 0 || pending} onClick={() => setStep((current) => current - 1)}>Back</Button>{step < 3 ? <Button disabled={!valid} onClick={next}>Continue</Button> : <Button disabled={!valid || pending} onClick={complete}>{pending ? "Transferring…" : "Confirm Transfer"}</Button>}</div></CardContent></Card><aside className="space-y-4"><AssetPreview asset={asset} /><CurrentAssignment asset={asset} /><NewAssignmentCard details={details} /><TransferHistory completed={completed} /><Help /></aside></div></main>;
}
function TermsStep({ terms, setTerms }: { terms: boolean[]; setTerms: (terms: boolean[]) => void }) { return <section><h2 className="text-base font-semibold">3. Terms & Conditions</h2><p className="mb-4 text-xs text-muted-foreground">Confirm the transfer responsibility and asset condition.</p><div className="space-y-3 rounded-md border p-4"><div className="rounded-md border border-info-border bg-info p-3 text-sm text-info-foreground"><strong>Current Asset Condition: Good</strong><p className="mt-1 text-xs">The asset condition is retained during this transfer.</p></div>{transferTerms.map((term, index) => <label key={term} className="flex gap-3 rounded-md border p-3 text-sm"><input type="checkbox" checked={terms[index]} className="mt-0.5 size-4 accent-primary" onChange={(event) => { const next = [...terms]; next[index] = event.target.checked; setTerms(next); }} />{term}</label>)}</div></section>; }
function ReviewStep({ asset, details, accepted }: { asset: TransferAsset; details: NewAssignment; accepted: boolean }) { return <section><h2 className="text-base font-semibold">4. Review & Confirm</h2><p className="mb-4 text-xs text-muted-foreground">Verify the transfer before completing it.</p><div className="grid gap-4 md:grid-cols-2"><DetailsCard title="Current Assignment" rows={[["Custodian", asset.custodian], ["Department", asset.department], ["Location", asset.location]]} /><DetailsCard title="New Assignment" rows={[["Custodian", details.custodian], ["Department", details.department], ["Office", details.office], ["Location", details.location], ["Transfer date", details.transferDate], ["Reason", details.reason]]} /></div><div className="mt-4 rounded-md border border-warning-border bg-warning p-3 text-xs text-warning-foreground">Terms accepted: <strong>{accepted ? "Yes" : "No"}</strong>. Completing this static workflow preserves the current assignment in its local history preview.</div></section>; }
function AssetPreview({ asset }: { asset?: TransferAsset }) { return <Card><CardContent className="p-4"><p className="mb-3 text-xs font-semibold">Asset Preview</p>{asset ? <div className="space-y-3"><div className="flex gap-3"><span className="grid size-14 place-items-center rounded bg-muted"><Laptop className="size-7 text-muted-foreground" /></span><div><p className="font-semibold">{asset.name}</p><p className="font-mono text-xs text-primary">{asset.assetTag}</p><Badge variant="info" className="mt-1">Assigned</Badge></div></div><DetailsCard rows={[["Property No.", asset.propertyNumber], ["Serial Number", asset.serialNumber], ["Category", asset.category], ["Brand / Model", asset.brandModel], ["Condition", asset.condition]]} /></div> : <p className="text-sm text-muted-foreground">Select an assigned asset to preview it.</p>}</CardContent></Card>; }
function CurrentAssignment({ asset }: { asset?: TransferAsset }) { return <Card><CardContent className="p-4"><p className="mb-3 text-xs font-semibold">Current Assignment</p>{asset ? <DetailsCard rows={[["Custodian", asset.custodian], ["Department", asset.department], ["Office", asset.office], ["Location", asset.location], ["Assigned", "Jan 15, 2025"], ["Purpose", "Faculty workstation"]]} /> : <p className="text-sm text-muted-foreground">Current assignment will appear here.</p>}</CardContent></Card>; }
function NewAssignmentCard({ details }: { details: NewAssignment }) { return <Card><CardContent className="p-4"><p className="mb-3 text-xs font-semibold">New Assignment Preview</p><DetailsCard rows={[["Custodian", details.custodian || "—"], ["Department", details.department || "—"], ["Location", details.location || "—"], ["Transfer date", details.transferDate || "—"]]} /></CardContent></Card>; }
function TransferHistory({ completed }: { completed: boolean }) { return <Card><CardContent className="p-4"><p className="mb-3 flex items-center gap-2 text-xs font-semibold"><History className="size-4 text-primary" />Transfer History</p><div className="space-y-3 text-xs">{completed && <p><strong className="text-success-foreground">Transfer completed</strong><br /><span className="text-muted-foreground">Just now · Static UI workflow</span></p>}<p><strong>Assigned to Juan Dela Cruz</strong><br /><span className="text-muted-foreground">Jan 15, 2025 · ICT Office - Room 203</span></p><p><strong>Acquired / Registered</strong><br /><span className="text-muted-foreground">Dec 01, 2024 · ICT Storage</span></p></div></CardContent></Card>; }
function Help() { return <div className="rounded-md border border-info-border bg-info p-4 text-xs text-info-foreground"><strong>Help</strong><ul className="mt-2 space-y-1.5"><li className="flex gap-2"><Check className="size-3.5" />Transfer assigned assets only.</li><li className="flex gap-2"><Check className="size-3.5" />Ensure the new custodian accepts responsibility.</li><li className="flex gap-2"><Check className="size-3.5" />Transfers are tracked for audit.</li></ul><div className="mt-4 border-t border-info-border pt-3"><strong>Next Steps After Transfer</strong><p className="mt-1">Asset remains Assigned. The new custodian is notified and the transfer record can be printed.</p></div></div>; }
function DetailsCard({ title, rows }: { title?: string; rows: string[][] }) { return <div className="space-y-2 text-xs">{title && <p className="font-semibold">{title}</p>}{rows.map(([label, value]) => <div key={label} className="flex justify-between gap-3"><span className="text-muted-foreground">{label}</span><strong className="text-right">{value}</strong></div>)}</div>; }
